# Generated by Django 4.1.7 on 2023-04-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_homepage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='homepage',
            name='title',
            field=models.CharField(default='My Homepage', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='background_photo',
            field=models.ImageField(upload_to='static/homepage_img'),
        ),
    ]
