# Generated by Django 4.1.7 on 2023-04-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='fax',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
