# Generated by Django 4.1.7 on 2023-04-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_office_fax_office_website_alter_office_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='fax',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='office',
            name='title',
            field=models.CharField(default='Office', max_length=255),
        ),
        migrations.AlterField(
            model_name='office',
            name='website',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
