# Generated by Django 4.1.7 on 2023-04-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_office_fax_alter_office_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='fax',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
