# Generated by Django 4.1.7 on 2023-04-02 18:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_aboutsection_delete_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(upload_to='static/aboutpage_img'),
        ),
    ]
