# Generated by Django 4.1.7 on 2023-04-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_aboutsection_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberKBG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='team_images/')),
            ],
        ),
    ]
