# Generated by Django 4.1.7 on 2023-04-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_teammemberkbg'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberKBGRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='static/Team_image')),
            ],
        ),
        migrations.AlterField(
            model_name='teammemberkbg',
            name='image',
            field=models.ImageField(upload_to='static/Team_image'),
        ),
    ]
